apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-root
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: resilience-root-ca
  namespace: resilience
spec:
  isCA: true
  commonName: resilience-root-ca
  secretName: resilience-root-ca-secret
  issuerRef:
    name: selfsigned-root
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: resilience-ca-issuer
  namespace: resilience
spec:
  ca:
    secretName: resilience-root-ca-secret
