apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: resilience
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

    # Rate limiting (obrigatório): agressivo no /work
    nginx.ingress.kubernetes.io/limit-req-status-code: "429"
    nginx.ingress.kubernetes.io/limit-conn-status-code: "429"

    # WAF básico (opcional recomendado)
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
spec:
  tls:
    - hosts:
        - api.resilience.local
        - auth.resilience.local
        - dash.resilience.local
        - grafana.resilience.local
      secretName: resilience-ingress-tls
  rules:
    - host: api.resilience.local
      http:
        paths:
          - path: /work
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80
    - host: auth.resilience.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth
                port:
                  number: 8000
    - host: dash.resilience.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashboard
                port:
                  number: 80
    - host: grafana.resilience.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: obs-grafana
                port:
                  number: 80
